name: Lint
on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]

jobs:
  format:
    name: Lint
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Flake Check
        uses: DeterminateSystems/flake-checker-action@main
      - name: Fmt check
        run: |
          nix run nixpkgs#nixfmt-rfc-style -- --check **/*.nix
      - name: Lint check
        run: |
          for file in **/*.nix; do
              nix run nixpkgs#nil -- diagnostics $file
          done
